version: 0.0
os: windows
files:
  - source: /aspnetapp/build_output
    destination: c:/inetpub/wwwroot/aspnetapp
 hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
     

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
     # runas: root
