version: 0.0
os: windows
files:
  - source: dotnet-docker-samples-master/build_output
    destination: c:/inetpub/wwwroot/dotnet-docker-samples-master
 
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
     
  ApplicationStart:
    - location: scripts/start_service
      timeout: 300   
