version: 0.2

env:
  variables:
    PROJECT: aspnet123
    DOTNET: 2.0
phases:
    install:
        runtime-versions:
            dotnet: 3.0
  
    build:
        commands:
           - echo Build started  on `date`
           - dotnet build -c Release ./aspnetapp/aspnetapp.csproj
artifacts:
  files:
    - '**/*'
  base-directory: 'C:\codebuild\artifacts\_PublishedWebsites\${env:PROJECT}_Package\Archive\'


commands:
     
