version: 0.2

env:
  variables:
    PROJECT: aspnet123
    DOTNET: 2.0
phases:
    install:
        runtime-versions:
            dotnet: 3.0
  
    build:
        commands:
           - echo Build started  on `date`
           - dotnet build -c Release ./aspnetapp/aspnetapp.csproj
artifacts:
 files:
    - CodeBuild-SampleCore/build_output/**/*
    - scripts/**/*
    - appspec.yml    
