version: 0.2

env:
  variables:
    PROJECT: aspnet123
    DOTNET: 3.0
phases:
    install:
        runtime-versions:
            dotnet: 3.0
  
    build:
        commands:
           - echo Build started on `date`
           - dotnet build -c Release aspnetapp/aspnetapp.csproj
           - dotnet publish -c release -o ./build_output aspnetapp/aspnetapp.csproj
artifacts:
  files:
     - aspnetapp/build_output/**/*
     - scripts/**/*
     - appspec.yml
